version: "3.4"
x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"

services:
  l3_execution_engine:
    image: gcr.io/evmchain/taiko-geth:eldfell
    restart: unless-stopped
    pull_policy: always
    stop_grace_period: 3m
    env_file:
      - .env.l3
    volumes:
      - l3_execution_engine_data:/data/taiko-geth
    ports:
      - "${PORT_L3_EXECTION_ENGINE_METRICS}:6060"
      - "${PORT_L3_EXECTION_ENGINE_HTTP}:8545"
      - "${PORT_L3_EXECTION_ENGINE_WS}:8546"
      - "${PORT_L3_EXECTION_ENGINE_P2P}:30303"
      - "${PORT_L3_EXECTION_ENGINE_P2P}:30303/udp"
    command:
      - --taiko
      - --networkid
      - "${CHAIN_ID}"
      - --syncmode
      - full
      - --gcmode
      - archive
      - --datadir
      - /data/taiko-geth
      - --metrics
      - --metrics.expensive
      - --metrics.addr
      - "0.0.0.0"
      - --bootnodes
      - ${BOOT_NODES}
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.vhosts
      - "*"
      - --http
      - --http.api
      - debug,eth,net,web3,txpool,taiko
      - --http.addr
      - "0.0.0.0"
      - --http.vhosts
      - "*"
      - --ws
      - --ws.api
      - debug,eth,net,web3,txpool,taiko
      - --ws.addr
      - "0.0.0.0"
      - --ws.origins
      - "*"
      - --txpool.locals
      - ${TXPOOL_LOCALS}
    <<: *logging

  l3_taiko_client_driver:
    image: gcr.io/evmchain/taiko-client:eldfell
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l3_execution_engine
    env_file:
      - .env.l3
    volumes:
      - l3_execution_engine_data:/data/taiko-geth
      - ./script/l3:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-driver.sh"
    <<: *logging

  l3_taiko_client_prover_relayer:
    image: gcr.io/evmchain/taiko-client:eldfell
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l3_execution_engine
      - l3_taiko_client_driver
      - l3_zkevm_chain_prover_rpcd
    env_file:
      - .env.l3
    volumes:
      - ./script/l3:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-prover-relayer.sh"
    <<: *logging

  l3_taiko_client_proposer:
    image: gcr.io/evmchain/taiko-client:eldfell
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - l3_execution_engine
      - l3_taiko_client_driver
    env_file:
      - .env.l3
    volumes:
      - ./script/l3:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-proposer.sh"
    <<: *logging

  l3_zkevm_chain_prover_rpcd:
    image: gcr.io/evmchain/eldfell-proverd:latest
    restart: unless-stopped
    ports:
      - "${PORT_ZKEVM_CHAIN_PROVER_RPCD}:9000"
    pull_policy: always
    env_file:
      - .env.l3
    volumes:
      - ./script/l3:/script
      - l3_zkevm_chain_prover_rpcd_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-zkevm-chain-rpcd.sh"
    <<: *logging

  l3_prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    env_file:
      - .env.l3
    ports:
      - ${PORT_PROMETHEUS}:9090
    depends_on:
      - l3_execution_engine
      - l3_taiko_client_driver
    volumes:
      - ./docker/prometheus/l3:/etc/prometheus
      - l3_prometheus_data:/prometheus
    command:
      - --log.level=debug
      - --config.file=/etc/prometheus/prometheus.yml
    <<: *logging

  l3_grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
      - .env.l3
    ports:
      - ${PORT_GRAFANA}:3000
    depends_on:
      - l3_execution_engine
      - l3_taiko_client_driver
      - l3_prometheus
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom/settings.ini
      - GF_PATHS_PROVISIONING=/etc/grafana/custom/provisioning
      - GF_LOG_LEVEL=WARN
    volumes:
      - ./docker/grafana/custom/settings.ini:/etc/grafana/custom/settings.ini
      - ./docker/grafana/custom/l3/provisioning/:/etc/grafana/custom/provisioning/
      - l3_grafana_data:/var/lib/grafana
    <<: *logging

volumes:
  l3_execution_engine_data:
  l3_zkevm_chain_prover_rpcd_data:
  l3_prometheus_data:
  l3_grafana_data:
