services:
  set-bridge-address-l1:
    image: nethsurge/protocol:surge-docs
    environment:
      FOUNDRY_PROFILE: layer1
      DOMAIN: ${L2_CHAIN_ID}
      ADDRESS: ${L2_BRIDGE_ADDRESS}
      NAME: ${BRIDGE_32_BYTES}
      PROXY_ADDRESS: ${L1_SHARED_ADDRESS_MANAGER}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    entrypoint:
      - sh
      - -c
    command: >
      'forge script ./script/shared/SetAddress.s.sol --fork-url "${L1_ENDPOINT_HTTP}" --broadcast -vvv'
  set-signal-service-address-l1:
    image: nethsurge/protocol:surge-docs
    environment:
      FOUNDRY_PROFILE: layer1
      DOMAIN: ${L2_CHAIN_ID}
      ADDRESS: ${L2_SIGNAL_SERVICE_ADDRESS}
      NAME: ${SIGNAL_SERVICE_32_BYTES}
      PROXY_ADDRESS: ${L1_SHARED_ADDRESS_MANAGER}
      FORK_URL: ${L1_ENDPOINT_HTTP}
      PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    entrypoint:
      - sh
      - -c
    command: >
      'forge script ./script/shared/SetAddress.s.sol --fork-url "${L1_ENDPOINT_HTTP}" --broadcast -vvv'
    networks:
      - surge
    profiles:
      - set-signal-service

  set-bridge-address-l2:
    image: nethsurge/protocol:surge-docs
    environment:
      FOUNDRY_PROFILE: layer1
      DOMAIN: ${L1_CHAIN_ID}
      ADDRESS: ${L1_BRIDGE_ADDRESS}
      NAME: ${BRIDGE_32_BYTES}
      PROXY_ADDRESS: ${L2_SHARED_ADDRESS_MANAGER}
      FORK_URL: http://l2-nethermind-execution-client:${L2_HTTP_PORT}
      PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    entrypoint:
      - sh
      - -c
    command: >
      'forge script ./script/shared/SetAddress.s.sol --fork-url http://l2-nethermind-execution-client:${L2_HTTP_PORT} --broadcast -vvv'
    networks:
      - surge
    profiles:
      - set-bridge

  set-signal-service-address-l2:
    image: nethsurge/protocol:surge-docs
    environment:
      FOUNDRY_PROFILE: layer1
      DOMAIN: ${L1_CHAIN_ID}
      ADDRESS: ${L2_SIGNAL_SERVICE_ADDRESS}
      NAME: ${SIGNAL_SERVICE_32_BYTES}
      PROXY_ADDRESS: ${L2_SHARED_ADDRESS_MANAGER}
      FORK_URL: http://l2-nethermind-execution-client:${L2_HTTP_PORT}
      PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
    entrypoint:
      - sh
      - -c
    command: >
      'forge script ./script/shared/SetAddress.s.sol --fork-url http://l2-nethermind-execution-client:${L2_HTTP_PORT} --broadcast -vvv'
    networks:
      - surge
    profiles:
      - set-signal-service

networks:
  surge:
    name: surge-network
    external: true